# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gneiting2002 <- function(x, y, a, c, beta, same = FALSE) {
    .Call(`_spmeshed_gneiting2002`, x, y, a, c, beta, same)
}

Cov_matern <- function(x, y, sigmasq, phi, nu, tausq, same, nThreads = 1L) {
    .Call(`_spmeshed_Cov_matern`, x, y, sigmasq, phi, nu, tausq, same, nThreads)
}

Cov_matern2 <- function(x, y, phi, same, twonu) {
    .Call(`_spmeshed_Cov_matern2`, x, y, phi, same, twonu)
}

Cov_matern_h <- function(h, sigmasq, phi, nu, tausq) {
    .Call(`_spmeshed_Cov_matern_h`, h, sigmasq, phi, nu, tausq)
}

Cov_powexp_h <- function(h, sigmasq, phi, nu, tausq) {
    .Call(`_spmeshed_Cov_powexp_h`, h, sigmasq, phi, nu, tausq)
}

blanket <- function(parents, children, names, block_ct_obs) {
    .Call(`_spmeshed_blanket`, parents, children, names, block_ct_obs)
}

coloring <- function(blanket, block_names, block_ct_obs) {
    .Call(`_spmeshed_coloring`, blanket, block_names, block_ct_obs)
}

kthresholdscp <- function(x, k) {
    .Call(`_spmeshed_kthresholdscp`, x, k)
}

part_axis_parallel <- function(coords, Mv, n_threads, verbose = FALSE) {
    .Call(`_spmeshed_part_axis_parallel`, coords, Mv, n_threads, verbose)
}

part_axis_parallel_fixed <- function(coords, thresholds, n_threads) {
    .Call(`_spmeshed_part_axis_parallel_fixed`, coords, thresholds, n_threads)
}

mesh_graph_cpp <- function(layers_descr, Mv, verbose = TRUE) {
    .Call(`_spmeshed_mesh_graph_cpp`, layers_descr, Mv, verbose)
}

knn_naive <- function(x, search_here, weights) {
    .Call(`_spmeshed_knn_naive`, x, search_here, weights)
}

mesh_graph_hyper <- function(bucbl, bavail, na_which, centroids, avcentroids, avblocks, k = 1L) {
    .Call(`_spmeshed_mesh_graph_hyper`, bucbl, bavail, na_which, centroids, avcentroids, avblocks, k)
}

lmc_mgp_mcmc <- function(y, X, coords, k, parents, children, layer_names, layer_gibbs_group, indexing, indexing_obs, set_unif_bounds_in, beta_Vi, tausq_ab, matern_twonu, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, mcmc_startfrom = 0L, num_threads = 1L, adapting = FALSE, forced_grid = TRUE, verbose = FALSE, debug = FALSE, print_every = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_lambda = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_spmeshed_lmc_mgp_mcmc`, y, X, coords, k, parents, children, layer_names, layer_gibbs_group, indexing, indexing_obs, set_unif_bounds_in, beta_Vi, tausq_ab, matern_twonu, start_w, lambda, lambda_mask, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, mcmc_startfrom, num_threads, adapting, forced_grid, verbose, debug, print_every, sample_beta, sample_tausq, sample_lambda, sample_theta, sample_w)
}

cube_tcrossprod <- function(x) {
    .Call(`_spmeshed_cube_tcrossprod`, x)
}

summary_list_mean <- function(x) {
    .Call(`_spmeshed_summary_list_mean`, x)
}

summary_list_q <- function(x, q) {
    .Call(`_spmeshed_summary_list_q`, x, q)
}

