# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caching_pairwise_compare_uci <- function(coords, indexing, names, ct_obs) {
    .Call(`_spmeshed_caching_pairwise_compare_uci`, coords, indexing, names, ct_obs)
}

blanket <- function(parents, children, names, block_ct_obs) {
    .Call(`_spmeshed_blanket`, parents, children, names, block_ct_obs)
}

coloring <- function(blanket, block_names, block_ct_obs) {
    .Call(`_spmeshed_coloring`, blanket, block_names, block_ct_obs)
}

kthresholdscp <- function(x, k) {
    .Call(`_spmeshed_kthresholdscp`, x, k)
}

part_axis_parallel <- function(coords, Mv, n_threads, verbose = FALSE) {
    .Call(`_spmeshed_part_axis_parallel`, coords, Mv, n_threads, verbose)
}

part_axis_parallel_fixed <- function(coords, thresholds, n_threads) {
    .Call(`_spmeshed_part_axis_parallel_fixed`, coords, thresholds, n_threads)
}

mesh_graph_cpp <- function(layers_descr, Mv, verbose = TRUE) {
    .Call(`_spmeshed_mesh_graph_cpp`, layers_descr, Mv, verbose)
}

knn_naive <- function(x, search_here, weights) {
    .Call(`_spmeshed_knn_naive`, x, search_here, weights)
}

mesh_graph_hyper <- function(bucbl, bavail, na_which, centroids, avcentroids, avblocks, k = 1L) {
    .Call(`_spmeshed_mesh_graph_hyper`, bucbl, bavail, na_which, centroids, avcentroids, avblocks, k)
}

lmc_mgp_mcmc <- function(y, X, coords, k, parents, children, layer_names, layer_gibbs_group, indexing, indexing_obs, set_unif_bounds_in, beta_Vi, tausq_ab, start_w, sigmasq, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, adapting = FALSE, forced_grid = TRUE, verbose = FALSE, debug = FALSE, print_every = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_lambda = TRUE, sample_theta = TRUE, sample_w = TRUE) {
    .Call(`_spmeshed_lmc_mgp_mcmc`, y, X, coords, k, parents, children, layer_names, layer_gibbs_group, indexing, indexing_obs, set_unif_bounds_in, beta_Vi, tausq_ab, start_w, sigmasq, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, adapting, forced_grid, verbose, debug, print_every, sample_beta, sample_tausq, sample_lambda, sample_theta, sample_w)
}

